name: KitsGUIPlus
main: com.SirLinkups.kitsgui.Core
authors: [Linkups, SirBlobman]
version: 1.0
commands:
   kit:
      description: Open the GUI for the kits
      aliases: [kits]
      usage: /<command>
      permission: kitsgui.kits
   kitsguiplus:
      description: Main command
      aliases: [kgp]
      usage: /<command>
   kitshop:
     description: Open the shop for donator kits
     alias: [ks]
     usage: /<command>