name: KitsGUIPlus
main: com.SirLinkups.kitsgui.Core
authors: [SirBlobman, Linkups]
version: 1.0
commands:
   createkit:
     description: Create a new kit
     aliases: [makekit, newkit, addkit]
     usage: /<command> <name> <in shop (yes/no)> [price in coins]
   kit:
      description: Open the GUI for the kits
      aliases: [kits]
      usage: /<command>
      permission: kitsgui.kits
   kitsguiplus:
      description: Main command
      aliases: [kgp]
      usage: /<command>
   kitshop:
     description: Open the shop for donator kits
     alias: [ks]
     usage: /<command>