name: KitsGUIPlus
main: com.SirLinkups.kitsgui.Core
authors: [Linkups, SirBlobman]
version: 1.0
commands:
   kit:
      description: Open the GUI for the kits
      aliases: [kits]
      usage: /<command>
      permission: kitsgui.kits
      permission-message: '&cYou don''t have the permission &bkitsgui.kits'